### ISSUE TITLE
large page size

### ISSUE THREAD

**Issue by Haroenv** [derhuerst/berlin-subway-guide#1]
The page is currently 21 MB large, and this gets completely downloaded, regardless if you actually watch every image. I suggest using some library for lazy loading or implementing it yourself.

**Comment by derhuerst** [comment]
I thought about this as well. However, I intend this website to work in a very old-school way, i.e. saving the website from your browser to disk. Dynamic lazy-loading would be tricky then.

**Comment by derhuerst** [comment]
After using smaller pictures, it's still 14mb.

**Comment by derhuerst** [comment]
Will close this one. Even though I fully agree 14mb are a problem, I want the website to be easily saved to disk. Please reopen if you have a solution that let's you do both.
