### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by timaschew** [derhuerst/berlin-subway-guide#2]
There is also a related project, it's a project of two designer in Berlin, they created book of it

http://www.kathleen-gust.de/pages/ubuch.html

**Comment by derhuerst** [comment]
> http://www.kathleen-gust.de/pages/ubuch.html

Looks awesome!

I plan to complete this collection, but taking proper photos of those U5 stations in the east is hard.

AFAIK @tursics also began doing something similar, we will join forces now. 😄

**Comment by tursics** [comment]
@derhuerst By the end of this week I will send you some nice pics.
